# template for server
app:
  host-url: http://localhost
spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/jira
    # db - docker compose
    url: jdbc:postgresql://db:5432/jira
    username: jira
    password: JiraRush

